{% set name = "textual" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70869326c47b2118304e24a275548049a87ebab4628c853261b8e7dd9c2d3148

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --no-build-isolation -vv
requirements:
  host:
    - python >=3.7,<4
    - poetry-core >=1.2.0
    - pip
  run:
    - python >=3.7,<4
    - rich >=13.3.3
    - markdown-it-py >=2.1.0
    - typing-extensions >=4.4.0,<5.0.0
    - importlib-metadata >=4.11.3
test:
  imports:
    - textual
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Textualize/textual
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern Text User Interface framework
  dev_url: https://github.com/Textualize/textual
  doc_url: https://textual.textualize.io

extra:
  recipe-maintainers:
    - davidbrochart
    - carlodri
