{% set name = "textual" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa70b9f2fe43819afeea64dff355aee1610e1d55e9915df1cef5b0d6f86cb20d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<37]

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - rich >=10.7.0,<11
    - typing-extensions >=3.10.0,<4  # [py<38]

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/willmcgugan/textual
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Textual is a TUI (Text User Interface) framework for Python inspired by modern web development.
  dev_url: https://github.com/willmcgugan/textual

extra:
  recipe-maintainers:
    - carlodri
