{% set name = "textual" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 516bf4db05830e70f9806828610a1a00de08068d984d329dbecc8dbef5d71ab7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4
    - rich >=12.6,<13
    - typing-extensions >=4,<5
    - nanoid >=2.0,<3
    - importlib-metadata >=4.11.3,<5

test:
  imports:
    - textual
    - textual.layouts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Textualize/textual
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Textual is a TUI (Text User Interface) framework for Python inspired by modern web development.
  dev_url: https://github.com/Textualize/textual

extra:
  recipe-maintainers:
    - carlodri
