{% set name = "textual" %}
{% set version = "0.56.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/textual-{{ version }}.tar.gz
  sha256: 9549a005a31658cd4dce7f73a247bc699b6173c74afc52c5dfdddb0afd4a67e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.2.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - markdown-it-py >=2.1.0
    - rich >=13.3.3
    - typing-extensions >=4.4.0,<5.0.0
  run_constrained:
    - tree-sitter >=0.20.1,<0.21.0
    - tree_sitter_languages >=1.7.0

test:
  imports:
    - textual
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Textualize/textual
  license: MIT
  license_file: LICENSE
  summary: Modern Text User Interface framework
  dev_url: https://github.com/Textualize/textual
  doc_url: https://textual.textualize.io

extra:
  recipe-maintainers:
    - davidbrochart
    - carlodri
    - xhochy
